In [1]:
import numpy as np
from scipy import optimize

c = np.array([-3, -4], dtype = np.float64)
G = np.array([[1, 4], [2, 3], [2, 1]], dtype = np.float64)
h = np.array([1700, 1400, 1000], dtype = np.float64)
sol = optimize.linprog(c, A_ub=G, b_ub=h, bounds=(0, None))
print(sol.x)
print(sol.fun)

[399.99988463 199.99996114]
-1999.9994984688606


In [3]:
import numpy as np
import cvxopt

p = cvxopt.matrix(np.array([[2, 1], [1, 2]], dtype=np.float64))
q = cvxopt.matrix(np.array([2, 4], dtype=np.float64))

sol = cvxopt.solvers.qp(p, q)
print(np.array(sol["x"]))
print(np.array(sol["primal objective"]))


[[ 2.22044605e-16]
 [-2.00000000e+00]]
-4.0


In [5]:
import numpy as np
import cvxopt

P = cvxopt.matrix(np.array([[2, 1], [1, 2]], dtype=np.float64))
q = cvxopt.matrix(np.array([2, 4], dtype=np.float64))
A = cvxopt.matrix(np.array([[1, 1]], dtype=np.float64))
b = cvxopt.matrix(np.array([0], dtype=np.float64))

sol = cvxopt.solvers.qp(P, q, A=A, b=b)
print(np.array(sol["x"]))
print(np.array(sol["primal objective"]))


[[ 1.]
 [-1.]]
-1.0000000000000016


In [6]:
import numpy as np
import cvxopt

P = cvxopt.matrix(np.array([[2, 1], [1, 2]], dtype=np.float64))
q = cvxopt.matrix(np.array([2, 4], dtype=np.float64))
G = cvxopt.matrix(np.array([[2, 3]], dtype=np.float64))
h = cvxopt.matrix(np.array([3], dtype=np.float64))

sol = cvxopt.solvers.qp(P, q, G=G, h=h)
print(np.array(sol["x"]))
print(np.array(sol["primal objective"]))


     pcost       dcost       gap    pres   dres
 0:  1.8858e+00  2.9758e-01  2e+00  5e-18  2e+00
 1: -2.1066e+00 -2.1546e+00  5e-02  2e-16  7e-01
 2: -3.9999e+00 -4.0665e+00  7e-02  3e-16  2e-16
 3: -4.0000e+00 -4.0007e+00  7e-04  1e-15  1e-16
 4: -4.0000e+00 -4.0000e+00  7e-06  3e-16  6e-17
 5: -4.0000e+00 -4.0000e+00  7e-08  9e-16  2e-16
Optimal solution found.
[[-2.45940172e-09]
 [-2.00000001e+00]]
-4.0


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import gd

def f(xx):
    x = xx[0]
    y = xx[1]
    return 5 * x**2 - 6 * x * y + 3 * y**2 + 6 * x - 6 * y

def df(xx):
    x = xx[0]
    y = xx[1]
    return np.array([10 * x - 6 *])